### ISSUE TITLE
Fake data in Entity with relationships

### ISSUE THREAD

**Issue by anton-kasperovich** [willdurand/BazingaFakerBundle#14]
I has two entities, for example: Country and City. City has relationship with Country (by country_id):

``` yml
    entities:
       Entity\Country:
            number: 100
            custom_formatters:
                code: { method: countryCode }
                title: { method: country }
       Entity\City:
            number: 20
            custom_formatters:
                country: { method: randomNumber, parameters: [1,2,3,4,5] }
```

With country or any standalone entity i don't have any problem, all is ok. But how now i can set country_id in City if in City (entity) i have:

``` php
    /**
     * Set country
     *
     * @param \Entity\Country $country
     * @return City
     */
    public function setCountry(\Entity\Country $country = null)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return \Entity\Country 
     */
    public function getCountry()
    {
        return $this->country;
    }
```

I try randomNumber or randomElement, but they not work for me like i expected, country_id is NULL after populate City table.
