### ISSUE TITLE
how to change locale?

### ISSUE THREAD

**Issue by Lewik** [willdurand/BazingaFakerBundle#39]
how to change locale?
Passing arguments to service definitions makes nothing.

**Comment by willdurand** [comment]
Hi!

It is probably a bit hidden, but it is written in the [doc](https://github.com/willdurand/BazingaFakerBundle/blob/master/Resources/doc/index.md#reference-configuration). Actually, you can configure the locale in the bundle's configuration section (for instance, in the `app/config/config.yml` file):

```yaml
bazinga_faker:
    seed:       1234
    locale:     en_GB
    populator:  Your\Own\Populator
    entity:     Your\Own\EntityPopulator
```
