### ISSUE TITLE
Many to Many relationships

### ISSUE THREAD

**Issue by emericspiroux** [willdurand/BazingaFakerBundle#44]
Hi, 
I need to make faker result in my jointure table product_category but it's not an entity, it's just a relation :
``` 
manyToMany:
   categories:
      targetEntity: Category
      inversedBy: products
      joinTable:
        name: product_category
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          category_id:
            referencedColumnName: id
            unique: true
```

how can i do with yaml to fill my jointure table ?

thx a lot !
