### ISSUE TITLE
The "faker.populator" service or alias has been removed

### ISSUE THREAD

**Issue by titiyoyo** [willdurand/BazingaFakerBundle#51]
Hi,

I just tried to use this bundle in an sf4 project but I get the following error message after following documentation steps. 

Am I doing something wrong?

```
 The "faker.populator" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

Here is my config

```
# fconfig/packages/dev/bazinga_faker.yml
bazinga_faker:
    orm: doctrine
    entities:
        App\Entity\Business:
            number: 50
```
